### ISSUE TITLE
should not be rendered on server

### ISSUE THREAD

**Issue by srghma** [siberiacancode/google-recaptcha#2]
https://github.com/siberiacancode/google-recaptcha/blob/60bce2b882a76059a1dcc0839540fe5f09c60091/packages/react/src/components/GoogleReCaptchaCheckbox.tsx#L46C3-L46C28

should be replaced with 

useLayoutEffect

I think

**Comment by debabin** [comment]
Hello @srghma , thanks for your question

useIsomorphicLayoutEffect specially created for ssr

You can read more here https://usehooks-ts.com/react-hook/use-isomorphic-layout-effect

Also useEffect and useLayoutEffect don't work on the server. https://react.dev/reference/react/useEffect#caveats last point
